server:
  port: 1112

spring:
  application:
    name: eureka-server


eureka:
  instance:
    hostname: peer-b
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:123456@peer-a:1111/eureka/,http://admin:123456@peer-c:1113/eureka/
