server:
  port: 1111

spring:
  application:
    name: eureka-server


eureka:
  instance:
    hostname: peer-a
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:123456@peer-b:1112/eureka/,http://admin:123456@peer-c:1113/eureka/
