server:
  port: 7777

spring:
  application:
    name: hello-service-consumer-feign

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://peer-a:1111/eureka/,http://peer-b:1112/eureka/,http://peer-c:1113/eureka/

