server:
  port: 4444

spring:
  application:
    name: hello-service

eureka:
  client:
    service-url:
#      defaultZone: http://localhost:1111/eureka/,http://localhost:1112/eureka/
      defaultZone: http://peer-a:1111/eureka/,http://peer-b:1112/eureka/
