server:
  port: 1113

spring:
  application:
    name: eureka-server


eureka:
  instance:
    hostname: peer-c
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:123456@peer-a:1111/eureka/,http://admin:123456@peer-b:1112/eureka/
